### ISSUE TITLE
agree spamming

### ISSUE THREAD

**Issue by GitGud2018** [chrisreyn/Tap-Titans-2-Progress-Bot#1]
your script is doing it again
had to disable it and add it in a roundabout manner 
also I find it sad, that you don't want to add my "Level top Heroes every X seconds code", had to manually add it again :/
why not just add it to the main script, you can just disable it by leaving the value at 0, if you don't like it

**Comment by GitGud2018** [comment]
1. I turned off agree and just added a few clicks on the same coordinates into the press skill section, so it still periodically clicks that location when it checks for skill clicks
your code just perma spams that area like it is trying to do a CQ, and I don't want that, because too many taps / second looks too supicious
2. yeah no, those are two completely different things
your code just stops scrolling down all the way after some time to reduce the time it needs to do so and that is good too, I use that too
but mine just quickly opens hero tab, levels each top hero once and closes it inbetween the big actionseveryXseconds rotation
I don't have that set to 30 seconds, that's just a random value anyone can set however they want, I actually have it set to 10 seconds and it speeds up runs alot, because it keeps your top heroes as strong as possible all the time
my actionseveryXseconds is set rather high, because it takes up alot of time, so I don't want it to do that  often and also my Dimensional Shift is level 9, sometimes level 10, depending on what build I run, so my skill rotations just last that long
3. no idea what you mean with that
just drag and drop the .txt file into nox and then move it into the hiromacro documents folder, I can do that with file sizes in the hundreds of megabytes
my script is 35.5KB in size and there is no issue copying it

**Comment by chrisreyn** [comment]
see if it works (and if there are other quirks) before i roll the update out to the main branch. i just copied it from the code you posted before https://github.com/chrisreyn/Tap-Titans-2-Progress-Bot/blob/chrisreyn-SCpatch-4-30/SC%20PHoM%20(edit%20settings%20for%20CS)%20SEE%20UPDATE%20NOTES

im keeping my own agree/clanship/what have you on my code tho.

**Comment by GitGud2018** [comment]
Alright, I tested it and this is what I noticed:

- I think it spams "agree" because something is wrong in the random attack section, I am not sure why though - it correctly hits phom every 30 hitcount, but it ignores the hitcount for agree and just spams it
if you have tapping activated, you won't mind that, but I have it deactivated to keep taps / second lower to prevent bot detection, but that is just my personal preferance, so I can just remove the agree part from the random attack section, no big problem :D

- when you use laterun, it starts by scrolling the menu without opening the menu first, not sure if that is intentional, because you already have your menu open, when you start a late run?

- top heroes extra leveling every X seconds works fine

- is this part in the skill press section correct?
if #minutes < 16
			#colorRed = -1
			#colorBlue = 0
		else
			getRGB #colorRed #colorGreen #colorBlue 410 705
			#time = #time + 100
		endif

If I am getting this, right it should be > instead of <? to prevent it pressing skills until you actually have SC unlocked, in case it messed up during first skill leveling attempt. After minute 16 it has to assume SC is leveled now

- 
//level only top hero at this time
	if #minutes >= 100
		goto :levelHeroesPressLevelUp
	endif

100 is way too high imo, but this falls under the category of "everyone has to set their own timers", the code to set it is there and that's all that matters :-)

but alltogether it seems to work great, it levels skills and hero correctly, does CQ and prestiges, no problems there for me

**Comment by chrisreyn** [comment]
re: `#lateRun`, that's odd because it's not supposed to scroll at all and move directly to just heroes given the condition was

if _**#lateRun < 1**_ and #count < 2

Tho when i tested, yea, it does try to scroll still so... ????

-----
`is this part in the skill press section correct?`
Yea, it's meant to not check if SC is running early in the run because manni mana appears then, therefore i should have enough mana. It should be the same logic even if you dont have SC maxed right off the bat right? or no?
