### ISSUE TITLE
just unlock skills

### ISSUE THREAD

**Issue by maverik13** [chrisreyn/Tap-Titans-2-Progress-Bot#13]
i press the just unlock skills to 1 and it max hs sc and the others dont even touch them or lvl up them . i dont use sc tree i use cs and i want my skills to lvl 2 or 1

**Comment by atereshkov** [comment]
@maverik13 look at https://github.com/Tune389/Tap-Titans-2-Progress-Bot/issues/87

**Comment by maverik13** [comment]
yes my friend i have already saw this but how do i set up it in the script

**Comment by maverik13** [comment]
@atereshkov is there any chance to lvl up deadly strike hand of midas and warcry skill to any lvl i want? for example 5 lvl each

**Comment by chrisreyn** [comment]
maybe you just need to adjust the sleep duration to 30

for example
```
#timeDiff = #secondsTotal - #lastPressHoM
	if #timeDiff >= #intervalHoM and #intervalHoM > 0 and #colorRed == -1 and #colorBlue == 0
		#lastPressHoM = #secondsTotal
		touchPress 0 200 710
		sleep 15
		touchUp 0
		sleep 10
		touchPress 0 200 710
		sleep 15
		touchUp 0
		sleep 10
		#time = #time + 50
```

^ change all the sleep to 30. might help. if not, maybe a slightly bigger number. if still not, idk

**Comment by maverik13** [comment]
11
