### ISSUE TITLE
Boss fight loop

### ISSUE THREAD

**Issue by Gufis22** [chrisreyn/Tap-Titans-2-Progress-Bot#4]
Hello, i greatly appreciate all the work you do on this script, however there's one thing i can't seem to figure out a fix for. Every time my run is close to the end, script loops on clicking boss fight. I've tried waiting, but it just keeps pressing "fight boss" and "leave battle" without doing anything else. Also, how do i disable the little text that says all the steps the bot takes? (like "pressing HOM" and etc.)

**Comment by Fruitburst** [comment]
In this code section:

//click "Fight Boss"
	getColor #color 372 24
	if #color == 1076975 and #bossLoopCounter <= 4
		#bossLoopCounter = #bossLoopCounter + 1
		toast FightBoss1
		touchPress 0 390 36
		sleep #btnDelay
		#time = #time + #btnDelay
		goto :pressSkills
	endif
            #bossLoopCounter == 0
Remove goto :pressSkills

**Comment by rockfreak101** [comment]
Yup. Removing goto fixes the problem.
