### ISSUE TITLE
Bot crashes randomly since 2.9

### ISSUE THREAD

**Issue by maelstromsh** [chrisreyn/Tap-Titans-2-Progress-Bot#40]
Using memu with nova. Since 2.9 the bot has not made it through the night. By the morning the game is closed and Memu is on the home screen. When I check the game, it seems to have done the leveling heroes portion, but the sword master is not leveled at all. I assume that there is an error in leveling the sword master now, but I have no idea.

It seems to be happening randomly, as it will make it through the first run but then fail at some point.

**Comment by chrisreyn** [comment]
Did you upgrade Memu to 5.5.5 (july 12)? that's the only help i can give assuming you've followed everything else i mentioned in the readme. in the first few releases of Memu 5.5.X, mine also kept crashing and it only stopped until the 5.5.5 version. Overall (including the latest TT2 update), both tt2 and Hiro were more stable in 5.5.5, at least for me

regarding skipped swordmaster leveling, https://github.com/chrisreyn/Tap-Titans-2-Progress-Bot/issues/39#issuecomment-406218033

**Comment by maelstromsh** [comment]
Tested a few times on 5.5.5, seems to have fixed it. Thanks mate.
