### ISSUE TITLE
20mins of botting

### ISSUE THREAD

**Issue by jmblen** [chrisreyn/Tap-Titans-2-Progress-Bot#46]
20mins onwards.. the bot does not follow the command line var #runActionsEveryXSeconds 170
it always upgrade heroes less than a minute from the time it reaches 20mins onwards

im just opening this issue because im on pet push build.. the bot needs to tap to maximize pet attck
i have been reviewing the code but i just cant find out where the line that means " level up heroes every 30seconds after 20mins of bot play"

now upon observations #runActionsEveryXSeconds 170 will only follow the command twice at the start of script,,which means after 340 seconds run actions will be nullified

if #runActionsEveryXSeconds 600 it will be nullfied after 20mins of script run
after 20mins i cant find the default settings where it will level up heroes every after 30-40seconds onwards

**Comment by chrisreyn** [comment]
you can look for
```
//time dynamic skill interval clicks
			if #minutes > 10
				#runActionsEveryXSeconds = 50
			endif
		endif
	endif
```
add your own conditionals here. for your case, use smth like `if #mins > 20`

and also probably why your edits are overwritten because i already had smth like that  in my code which i just quoted above hehe

**Comment by jmblen** [comment]
thx
