### ISSUE TITLE
Which part control lvl Sword Master?

### ISSUE THREAD

**Issue by Sraw** [chrisreyn/Tap-Titans-2-Progress-Bot#48]
I cannot find an option to control the inerval of lvl up SM or even enable or disable lvl up.

The actual problem is that after disabling `#enableHeroes` as I'm using pet build to farm, the script never lvls up SM any more.

**Comment by chrisreyn** [comment]
leveling up past lvl 600 does nothing and it only levels up SM every new run. set your denomination to 'MAX'. if you want continuous SM level up (and idk why you would unless you cant initially reach lvl 600), fix your own `:openSwordMasterTab`

**Comment by Sraw** [comment]
I'm a newbie in this game so I cannot understand why "leveling up past lvl 600 does nothing"? Leveling up SM will obviously increase tap damage which will affect pet damage too. And as I am using pet build, pet's damage is my main damage source.
Could you explain it a little bit more? Thank you.

**Comment by chrisreyn** [comment]
@Sraw scaling for Sword Master level is horrible past 600. dont even bother. you get more from %tap damage from heroes and you only need until 600 to unlock skills and prestige

**Comment by Sraw** [comment]
Thank you, I've never tried tap damage from hero before.
