### ISSUE TITLE
Skills

### ISSUE THREAD

**Issue by Speiky55** [chrisreyn/Tap-Titans-2-Progress-Bot#52]
hey i wanted to aks is there a way to just max hs at start and leave all others at 1 because i use a hs build ?

**Comment by maelstromsh** [comment]
Use #JustUnlockSkills 1. It will still max HS no matter what.

**Comment by Speiky55** [comment]
but wit will max shadow clone i use just unlock 1 and i also changed the script like the issue with the just unlock 1

**Comment by Speiky55** [comment]
and is there a way to let the skill at this min lvl up to max so it would push at the end

**Comment by Speiky55** [comment]
this would be a nice update the random timer between 1-10 for secur to not get baned to max the skills and do a final push

**Comment by chrisreyn** [comment]
@Speiky55 it's in the wiki if you cant get `#justUnlockSkills 1` to work, but i honestly havent updated that code cuz i dont use it anymore sorry. im too lazy too and just work on my Mana Siphon skill so i can use all my skills whether new or end of run
