### ISSUE TITLE
Hero Info Panel

### ISSUE THREAD

**Issue by Hassliebe** [chrisreyn/Tap-Titans-2-Progress-Bot#6]
Sorry if i missed this issue earlier, i think i saw it mentioned somewhere. 

Script is just about perfect, thanks alot for all your work on it.

Only issue im still facing is that it sometimes gets stuck on opening hero information panel and wont close it.

Havent really been able to pinpoint it, so any help is appreciated =)

**Comment by chrisreyn** [comment]
i too have been experiencing this as of recent. such an odd thing because this wasnt the case in android 4

**Comment by Hassliebe** [comment]
Frequently restarting Nox helps me

**Comment by chrisreyn** [comment]
https://github.com/Tune389/Tap-Titans-2-Progress-Bot/issues/94

but essentially, just use Memu and still change the default launcher to smth like Nova
