### ISSUE TITLE
did you tested it in 2.10? 

### ISSUE THREAD

**Issue by Speiky55** [chrisreyn/Tap-Titans-2-Progress-Bot#60]
i am scared to use it i dont want to get banned;D

**Comment by Speiky55** [comment]
and i use your new script now what i need to change in line 249? because it says important to change it;D

**Comment by chrisreyn** [comment]
it's fine to use it.

line 249 overrides `#runActionsEveryXSeconds` at `#minutes = 10` so just take note that it has a lower value at 10 minutes onwards which I use. You're free to change/remove that of course
