### ISSUE TITLE
Fairies + ads?

### ISSUE THREAD

**Issue by limburgerrr** [chrisreyn/Tap-Titans-2-Progress-Bot#91]
Hello,
if I activate fairies and the ads come then the bot does not go back to botten but gets stuck with the ad is there a way to solve this?

yes i know i can disable them but i wanna know if there is a way too do this and let the bot wait for x second and then close the ad and go to botting again?

Greetz

**Comment by chrisreyn** [comment]
the ads dont all have a similar 'return to game' button. sometimes it's upper left or upper right or even center and i cant predict that. you'll have to turn it off

**Comment by limburgerrr** [comment]
thank you again sir
